### ISSUE TITLE
Quad renders differently on some systems (AMD GPU?)

### ISSUE THREAD

**Issue by def-** [def-/ddnet#177]
Without bug:
![ohnebug1](https://cloud.githubusercontent.com/assets/2335377/6835464/3a3a74f4-d33b-11e4-966d-b44ea2c6ee6d.png)
![ohnebug2](https://cloud.githubusercontent.com/assets/2335377/6835466/3a3cd00a-d33b-11e4-95f9-5cc7e9732468.png)
![ohnebug3](https://cloud.githubusercontent.com/assets/2335377/6835465/3a3b7ed0-d33b-11e4-9caf-6ff22597d86e.png)

With bug:
![mitbug1](https://cloud.githubusercontent.com/assets/2335377/6835461/3a3851d8-d33b-11e4-889f-5d81abca2163.png)
![mitbug2](https://cloud.githubusercontent.com/assets/2335377/6835463/3a390c72-d33b-11e4-8966-a6f2bbfc45f1.png)
![mitbug3](https://cloud.githubusercontent.com/assets/2335377/6835462/3a390704-d33b-11e4-8f97-c0a90a0dc5e3.png)

Reported by hi_leute_gll

**Comment by def-** [comment]
Seems to be fixed by gfx_quads_as_triangles 1, but still looks more pixelly (and that decreases performance): 
![unbenannt](https://cloud.githubusercontent.com/assets/2335377/6836100/85cb87ec-d33f-11e4-954c-76510ebbe08c.PNG)

**Comment by cinaera** [comment]
Pixelation probably caused by aliasing.
Performance decrease can maybe reduced by batching the draw calls together. In the current code for each quad there is a seperate drawcall, which can cause noticeable overhead on some drivers. Batching can be done by either using index buffers or simply build two triangles per quad

**Comment by def-** [comment]
Any idea if you could fix this? It's a potential tournament map ;)
